- chapter-8-recursion-and-Dynamic-Programming/8-1-Triple-Step.cpp
Added a simple recursive solution for finding number ways to climb the stairs.
> Added solution of ques 1 of Ch 8

- Ch 1.Arrays And Strings/1.Is Unique/1. Is_unique.cpp
> Update 1. Is_unique.cpp

- chapter-2-Linked-Lists/2-4-partition.cpp
A small bug, original code does not generate random numbers during for loop
> A small bug fixed

- Ch 4. Trees and Graphs /4-1-Route-Between-Nodes.cpp
Added a simple Breadth first search solution for finding if there is a route between nodes in a graph.
> Added solution for ques 1 of Ch 4

- chapter-8-recursion-and-Dynamic-Programming/8-5-Recursive-Multiply.cpp
Reverts careercup/CtCI-6th-Edition-cpp#14
> Revert "Added solution of ques 5 of Ch 8"

- Ch 1.Arrays And Strings/1.Is Unique/1. Is_unique.cpp
Implementation using bit vector which saves 8x space and an implementation using no data structures has been added.
> Additional implementations to Q1_1

- validateBST.cpp
This is my C++ implementation of the validate BST question. I have used a simple inorder traversal to check if the tree is a balanced search tree or not. My function passed all the test cases on hackerrank.
> validateBST.cpp

- Ch 1.Arrays And Strings/1.Is Unique/1. Is_unique.cpp
- Ch 1.Arrays And Strings/2.Check Permutation/1.Check_Permutation.cpp
Additional implementation for checking permutations using character count.
> Additional implementation for Q1_2

- Chapter-3-Stacks-and-Queues/C++14/3.2-StackMin.cpp
- Chapter-3-Stacks-and-Queues/C++14/3.3-StackOfPlates.cpp
- Chapter-3-Stacks-and-Queues/C++14/3.3-StackOfPlatesFU.cpp
- Chapter-3-Stacks-and-Queues/C++14/stack.hpp
Reverts careercup/CtCI-6th-Edition-cpp#24
> Revert "Solutions for task 2 and 3 of Chapter "Stacks and Queues", for C++14 (with templates, initializer lists and r-value references)"

- Chapter-3-Stacks-and-Queues/C++14/3.4-QueueViaStacks.cpp
- Chapter-3-Stacks-and-Queues/C++14/3.5-SortStack.cpp
- Chapter-3-Stacks-and-Queues/C++14/3.6-AnimalShelter.cpp
- Chapter-3-Stacks-and-Queues/C++14/queue.hpp
Solutions for task 4, 5 and 6 of Chapter "Stacks and Queues", for C++14 (with templates, initializer lists and r-value references).
> Stacks and Queues

- Ch 4. Trees and Graphs /4-2-Minimal-Tree.cpp
Added solution for 4.2 Minimal Tree
> Added 4-2-Minimal-Tree.cpp

- Ch 4. Trees and Graphs /C++14/4.1-RouteBetweenNodes.cpp
- Ch 4. Trees and Graphs /C++14/4.10i-CheckSubtree.cpp
- Ch 4. Trees and Graphs /C++14/4.10r-CheckSubtree.cpp
- Ch 4. Trees and Graphs /C++14/4.5-ValidateBST.cpp
- Ch 4. Trees and Graphs /C++14/4.6-Successor.cpp
- Ch 4. Trees and Graphs /C++14/4.7-BuildOrder.cpp
- Ch 4. Trees and Graphs /C++14/4.7d-BuildOrder.cpp
- Ch 4. Trees and Graphs /C++14/4.8-FirstCommonAncestor.cpp
- Ch 4. Trees and Graphs /C++14/4.8p-FirstCommonAncestor.cpp
- Ch 4. Trees and Graphs /C++14/4.9-BSTSequences.cpp
- Ch 4. Trees and Graphs /C++14/graph.hpp
- Ch 4. Trees and Graphs /C++14/graphtestutils.hpp
- Ch 4. Trees and Graphs /C++14/treenodeiterator.hpp
C++14 solutions for tasks 4.5 to 4.9 of the chapter Trees and Graphs.
Hi Krish,
I did solutions for tasks 4.5-4.10 of the chapter "Trees and Graphs".
I have modified graph.hpp from my previous commit. It is shorter and more clean now, my new and modified helper functions for grapts are in graphtestutils.hpp.
Also I have implemented a node iterator for trees. It is need to test all node pairs of a whole tree in the task 4.8 that task was enough hard to me. Iterators make a solution of 4.10 a bit cleaner and shorter, the file 4.10i.cpp contains a solution with iterators and 4.10r.cpp without them.
> Trees & Graphs

- chapter-8-recursion-and-Dynamic-Programming/8-8-Permutation-with-dups-alt.cpp
- chapter-8-recursion-and-Dynamic-Programming/8-9-parens-alt.cpp
This solution was ignored by the book despite hint #187. Even though it is less efficient, I find it useful to compare and contrast this solution with the existing solution.
> Add alternate 8-9 solution.

- Ch 4. Trees and Graphs /C++14/4.11-RandomNode.cpp
- Ch 4. Trees and Graphs /C++14/4.11m-RandomTree.cpp
- Ch 4. Trees and Graphs /C++14/4.12-PathsWithSum.cpp
- Ch 4. Trees and Graphs /C++14/4.8-FirstCommonAncestor.cpp
- Ch 4. Trees and Graphs /C++14/tree.hpp
- Ch 4. Trees and Graphs /C++14/treenodeiterator.hpp
- Ch 4. Trees and Graphs /C++14/treetestutils.hpp
- Ch 5. Bit Manipulation/C++14/5.1-Insertion.cpp
- Ch 5. Bit Manipulation/C++14/5.2-BinaryToString.cpp
- Ch 5. Bit Manipulation/C++14/5.3-FlipBitToWin.cpp
- Ch 5. Bit Manipulation/C++14/5.4-NextNumber.cpp
- Ch 5. Bit Manipulation/C++14/bitutils.hpp
Hi Krish.
I offer my C++14 solutions for tasks 4.11 and 4.12 of the chapter "4. Trees and Graphs". I have updated my templated Tree class, have done it more common, so it can hold user-defined nodes, like RandomNode from the task 4.11.
Additionally I offer C++14 solutions for tasks 5.1 to 5.4 of the chapter "5. Bit Manipulation".
> Trees and Graphs: C++14 solutions for tasks 4.11, 4.12 and Bit Manipulation: 5.1 to 5.4.

- chapter-8-recursion-and-Dynamic-Programming/8-2-Robot-in-a-Grid.cpp
It includes both an implementation without caching/memoization and an implementation with caching/memoization.
> Added C++ solution to Q8.2

- chapter-2-Linked-Lists/2-6-palindrome.cpp
Instead of calling isPalindromeRecur for all 3 test lists in the main function call, it now calls isPalindromeIter1 for the first list, isPalindromeIter2 for the second list and isPalindromeRecur for the final list.
> Changed the function calls in main() to include the 2 isPalindrome functions.

- Chapter-3-Stacks-and-Queues/C++14/3.2-StackMin.cpp
- Chapter-3-Stacks-and-Queues/C++14/3.3-StackOfPlates.cpp
- Chapter-3-Stacks-and-Queues/C++14/3.3-StackOfPlatesFU.cpp
- Chapter-3-Stacks-and-Queues/C++14/stack.hpp
Reverts careercup/CtCI-6th-Edition-cpp#25
> Revert "Revert "Solutions for task 2 and 3 of Chapter "Stacks and Queues", for C++14 (with templates, initializer lists and r-value references)""

- Ch 4. Trees and Graphs/C++14/AVLTree.cpp
For finding preorder traversal and height of an AVL Tree
> AVLTree.cpp

- Chapter-3-Stacks-and-Queues/3.2_stack_min.cpp
- Chapter-3-Stacks-and-Queues/3.3_stack_of_plastes
- Chapter-3-Stacks-and-Queues/3.4_queue_via_stacks
- Chapter-3-Stacks-and-Queues/3.5_sort_stack
- Chapter-3-Stacks-and-Queues/3.6_animal_shelter
- Chapter-4-tree-and-graph/4.10_check_subtree.cpp
- Chapter-4-tree-and-graph/4.11_random_node.cpp
- Chapter-4-tree-and-graph/4.2_minimal_tree.cpp
- Chapter-4-tree-and-graph/4.3_list_of_depths.cpp
- Chapter-4-tree-and-graph/4.4_check_balanced.cpp
- Chapter-4-tree-and-graph/4.5_validate_BST.cpp
- Chapter-4-tree-and-graph/4.6_successor.cpp
- Chapter-4-tree-and-graph/4.7_build_order.cpp
- Chapter-4-tree-and-graph/4.8_first_common_ancestor.cpp
- Chapter-4-tree-and-graph/4.9_BST_sequences.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.10_Paint_Fill.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.1_Triple_Step.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.2_Grid_Paths.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.3_Magic_Index.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.4_Power_Set.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.5_Recursive_Multiply.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.6_Tower_of_Hanoi.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.7_Permutations_without_Dups.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.8_Permutations_with_Dups.cpp
- chapter-8-recursion-and-Dynamic-Programming/8.9_Parens.cpp
A simple version of 3.2 and added in solutions 3.3,3.4,3.5,3.6
> 3.2_stack_min.cpp

- Ch 1.Arrays And Strings/3.URLify/URLify2.cpp
- Ch 12. C++/k_strings.txt
- Ch 12. C++/print_k_lines.cpp
- Chapter-16-moderate/test_word_freq
- Chapter-16-moderate/word_freq.cpp
…k to eliminate empty strings
Without this check it actually doesn't print the last k lines - (tested on Mac)
> Added a solution to q.12.1 - added a check to eliminate empty string which are pushed using getline

- Ch 1.Arrays And Strings/3.Palindrome Permutation/Palindrome Permutation.cpp
- Ch 1.Arrays And Strings/4.Palindrome_Permutation/4-pallindrome-permutations.cpp
Add bitwise version implementation to save space complexity of problem Palidrome Permutation
> (Palidrome Permutation) bitwise solution
